name: Build & push images for 'kc-ms'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs-archive/**'
      - '*/chart/**'

jobs:
  validate-docker-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Validate docker registry secrets are defined
      id: validate-docker-secrets
      run: |
        echo "Validating docker registry secrets are defined on the repository"

        FAIL=false

        validate_secret(){
          FIELD=$1
          VALUE=$2

          if [ -z "${VALUE}" ]; then
            echo "The secret ${FIELD} needs to be set on this repository."
            FAIL=true
          else
            echo "The secret ${FIELD} is set on this repository."
          fi
        }

        validate_secret DOCKER_USERNAME ${DOCKER_USERNAME}
        validate_secret DOCKER_PASSWORD ${DOCKER_PASSWORD}
        validate_secret DOCKER_REPOSITORY ${DOCKER_REPOSITORY}
        validate_secret DOCKER_REGISTRY ${DOCKER_REGISTRY}
        validate_secret DOCKER_IMAGE_FLEET ${DOCKER_IMAGE_FLEET}
        validate_secret DOCKER_IMAGE_VOYAGES ${DOCKER_IMAGE_VOYAGES}
        validate_secret GITOPS_EMAIL ${GITOPS_EMAIL}
        validate_secret GITOPS_TOKEN ${GITOPS_TOKEN}
        validate_secret GITOPS_ORG ${GITOPS_ORG}

        if [ "${FAIL}" = "true" ]; then
          exit 1
        fi
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_IMAGE_FLEET: ${{ secrets.DOCKER_IMAGE_FLEET }}
        DOCKER_IMAGE_VOYAGES: ${{ secrets.DOCKER_IMAGE_VOYAGES }}
        GITOPS_EMAIL: ${{ secrets.GITOPS_EMAIL }}
        GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        GITOPS_ORG: ${{ secrets.GITOPS_ORG }}

  build-docker-images:
    needs:
      validate-docker-secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: bump-version-action
      uses: ibm-cloud-architecture/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Appsody CLI
      id: install-appsody-cli
      uses: ibm-cloud-architecture/appsody-install-action@master
    - name: Build the fleet-ms docker image
      id: build-fleet-image
      run: |
        IMAGE_NAME="${DOCKER_REG}/${DOCKER_R}/${DOCKER_I}"
        docker login -u ${DOCKER_U} -p ${DOCKER_P} ${DOCKER_REG}

        echo "Build and push the docker image"
        cd ${WORKDIR}
        appsody build -v --tag ${IMAGE_NAME}:${IMAGE_TAG} --push
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_R: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_I: ${{ secrets.DOCKER_IMAGE_FLEET }}
        DOCKER_REG: ${{ secrets.DOCKER_REGISTRY }}
        WORKDIR: fleet-ms
        IMAGE_TAG: ${{ steps.bump-version-action.outputs.new_tag }}
    - name: Save fleet-ms app-deploy.yaml
      uses: actions/upload-artifact@v2
      with:
        name: fleetms-app-deploy.yaml
        path: fleet-ms/app-deploy.yaml
    - name: Build the voyages-ms docker image
      id: build-voyages-image
      run: |
        IMAGE_NAME="${DOCKER_REG}/${DOCKER_R}/${DOCKER_I}"
        docker login -u ${DOCKER_U} -p ${DOCKER_P} ${DOCKER_REG}

        echo "Build and push the docker image"
        cd ${WORKDIR}
        appsody build -v --tag ${IMAGE_NAME}:${IMAGE_TAG} --push
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_R: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_I: ${{ secrets.DOCKER_IMAGE_VOYAGES }}
        DOCKER_REG: ${{ secrets.DOCKER_REGISTRY }}
        WORKDIR: voyages-ms
        IMAGE_TAG: ${{ steps.bump-version-action.outputs.new_tag }}
    - name: Save voyages-ms app-deploy.yaml
      uses: actions/upload-artifact@v2
      with:
        name: voyagesms-app-deploy.yaml
        path: voyages-ms/app-deploy.yaml
  update-gitops:
    needs:
      build-docker-images
    runs-on: ubuntu-latest
    steps:
    - name: Configure git client
      id: configure-git
      uses: ibm-cloud-architecture/git-config-action@master
      with:
        user-email: ${{ secrets.GITOPS_EMAIL }}
        gitops-token: ${{ secrets.GITOPS_TOKEN }}
    - name: Retrieve fleet-ms app-deploy.yaml
      uses: actions/download-artifact@v2
      with:
        name: fleetms-app-deploy.yaml
        path: fleetms
    - name: Update fleet-ms app-deploy.yaml in GitOps repo
      id: update-fleet-gitops
      uses: ibm-cloud-architecture/appsody-gitops-update-action@master
      with:
        service-name: fleetms
        github-org: ${{ secrets.GITOPS_ORG }}
        gitops-repo-name: refarch-kc-gitops
    - name: Retrieve voyages-ms app-deploy.yaml
      uses: actions/download-artifact@v2
      with:
        name: voyagesms-app-deploy.yaml
        path: voyagesms
    - name: Update voyages-ms app-deploy.yaml in GitOps repo
      id: update-voyages-gitops
      uses: ibm-cloud-architecture/appsody-gitops-update-action@master
      with:
        service-name: voyagesms
        github-org: ${{ secrets.GITOPS_ORG }}
        gitops-repo-name: refarch-kc-gitops
